package com.mycompany.payroll.view;

import com.mycompany.payroll.controller.AttendanceController;
import com.mycompany.payroll.controller.EmployeeController;
import com.mycompany.payroll.controller.LeaveTypeController;
import com.mycompany.payroll.model.Attendance;
import com.mycompany.payroll.model.Employee;
import com.mycompany.payroll.model.LeaveType;
import java.sql.Timestamp;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Isuru Sankajith
 */
public class AttendanceListForm extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeListForm
     */
    public AttendanceListForm() {
        initComponents();
        findAllAttendance();
        cmbEmployee.setVisible(false);
        lblEmployee.setVisible(false);
        //LoadCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        AddAttendance = new javax.swing.JButton();
        UpdateEmployeeForm = new javax.swing.JButton();
        lblEmployee = new javax.swing.JLabel();
        cmbEmployee = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee From");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Attendance List");

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attendance Id", "Employee Id", "EMployee Name", "In Time", "Out Time"
            }
        ));
        tblAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAttendanceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAttendance);

        AddAttendance.setBackground(new java.awt.Color(0, 102, 102));
        AddAttendance.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddAttendance.setForeground(new java.awt.Color(204, 204, 204));
        AddAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddAttendance.setText("Add new");
        AddAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAttendanceActionPerformed(evt);
            }
        });

        UpdateEmployeeForm.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm.setText("Update");
        UpdateEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeFormActionPerformed(evt);
            }
        });

        lblEmployee.setText("Employee");

        cmbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(AddAttendance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateEmployeeForm)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateEmployeeForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeFormActionPerformed
        UpdateAttendanceDetailsForm updateAttendanceForm = new UpdateAttendanceDetailsForm();
        updateAttendanceForm.setVisible(true);
        updateAttendanceForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeFormActionPerformed

    private void AddAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAttendanceActionPerformed
        AddAttendanceForm addTransactionForm = new AddAttendanceForm();
        addTransactionForm.setVisible(true);
        addTransactionForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddAttendanceActionPerformed

    private void tblAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAttendanceMouseClicked
        try {
            int row = tblAttendance.getSelectedRow();
            int attendanceID = 0;
            Attendance attendance = new Attendance();

            if (row >= 0) {
                attendanceID = Integer.parseInt(tblAttendance.getModel().getValueAt(row, 0).toString());
                attendance.setAttendance_id(attendanceID);
                attendance.setIn_time(Timestamp.valueOf(tblAttendance.getModel().getValueAt(row, 3).toString()));
                attendance.setOut_time(Timestamp.valueOf(tblAttendance.getModel().getValueAt(row, 4).toString()));
                attendance.setEmployee_id(Integer.parseInt(tblAttendance.getModel().getValueAt(row, 1).toString()));
            }
            UpdateAttendanceDetailsForm updateAttendanceDetailsForm = new UpdateAttendanceDetailsForm(attendance);
            updateAttendanceDetailsForm.setVisible(true);
            updateAttendanceDetailsForm.setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblAttendanceMouseClicked
    private void LoadCombo() {
        try {
            EmployeeController employeeController = new EmployeeController();
            List<Employee> employeeList = employeeController.findAllEmployee();
            cmbEmployee.removeAllItems();

            for (int i = 0; i < employeeList.size(); i++) {
                Employee employee = employeeList.get(i);
                cmbEmployee.addItem(employee.getEmployeeId().toString());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAttendance;
    private javax.swing.JButton UpdateEmployeeForm;
    private javax.swing.JComboBox<String> cmbEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JTable tblAttendance;
    // End of variables declaration//GEN-END:variables

    private void findAllAttendance() {
        DefaultTableModel dtm = (DefaultTableModel) tblAttendance.getModel();
        dtm.setRowCount(0);
        try {
            AttendanceController objAttendanceController = new AttendanceController();
            List<Attendance> attendance = objAttendanceController.findAllAttendance();

            for (int i = 0; i < attendance.size(); i++) {
                Attendance e = attendance.get(i);
                Object[] data = {e.getAttendance_id(), e.getEmployee_id(), e.getFullName(),e.getIn_time(), e.getOut_time(),  e.getAttendance_date()};
                dtm.addRow(data);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
