package com.mycompany.payroll.view;

import com.mycompany.payroll.controller.EmployeeController;
import com.mycompany.payroll.model.Employee;
import com.mycompany.payroll.model.Shift;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Isuru Sankajith
 */
public class EmployeeListForm extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeListForm
     */
    public EmployeeListForm() {
        initComponents();
        findAllEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        AddEmployeetxt = new javax.swing.JButton();
        UpdateEmployeeForm = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee From");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee List");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "First Name", "Last Name", "Contact No:", "NIC", "Address", "Shift"
            }
        ));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployees);

        AddEmployeetxt.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt.setText("Add new");
        AddEmployeetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxtActionPerformed(evt);
            }
        });

        UpdateEmployeeForm.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm.setText("Update");
        UpdateEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateEmployeeForm)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddEmployeetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateEmployeeForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeFormActionPerformed
        try {
            int row = tblEmployees.getSelectedRow();
            int employeeID = 0;
            if (row >= 0) {
                employeeID = Integer.parseInt(tblEmployees.getModel().getValueAt(row, 0).toString());
            }
            Employee employee = new Employee();
            employee.setEmployeeId(employeeID);
            EmployeeController objEmployeeController = new EmployeeController();
            List<Employee> employees = objEmployeeController.findEmployeeDetailsForId(employee);
            Employee e = new Employee();
            for (int i = 0; i < employees.size(); i++) {
                e = employees.get(i);
            }
            UpdateEmployeeForm updateEmployeeForm = new UpdateEmployeeForm(e);
            updateEmployeeForm.setVisible(true);
            updateEmployeeForm.setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateEmployeeFormActionPerformed

    private void AddEmployeetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxtActionPerformed
        AddEmployeeForm employeeListForm = new AddEmployeeForm();
        employeeListForm.setVisible(true);
        employeeListForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxtActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        try {
            int row = tblEmployees.getSelectedRow();
            int employeeID = 0;
            if (row >= 0) {
                employeeID = Integer.parseInt(tblEmployees.getModel().getValueAt(row, 0).toString());
            }
            Employee employee = new Employee();
            employee.setEmployeeId(employeeID);
            EmployeeController objEmployeeController = new EmployeeController();
            List<Employee> employees = objEmployeeController.findEmployeeDetailsForId(employee);
            Employee e = new Employee();
            for (int i = 0; i < employees.size(); i++) {
                e = employees.get(i);
            }
            UpdateEmployeeForm updateEmployeeForm = new UpdateEmployeeForm(e);
            updateEmployeeForm.setVisible(true);
            updateEmployeeForm.setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblEmployeesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeetxt;
    private javax.swing.JButton UpdateEmployeeForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    private void findAllEmployees() {
        DefaultTableModel dtm = (DefaultTableModel) tblEmployees.getModel();
        dtm.setRowCount(0);
        try {
            EmployeeController objEmployeeController = new EmployeeController();
            List<Employee> employees = objEmployeeController.findAllEmployeeWithCategoryAndType();

            for (int i = 0; i < employees.size(); i++) {
                Employee e = employees.get(i);
                Shift shift = e.getShiftObj();
                Object[] data = {e.getEmployeeId(), e.getFirstName(), e.getLastName(), e.getContact(), e.getNic(), e.getAddress(), shift.getShift_name()};
                dtm.addRow(data);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
