package com.mycompany.payroll.view;

import com.mycompany.payroll.controller.EmployeeController;
import com.mycompany.payroll.controller.LeaveController;
import com.mycompany.payroll.model.Employee;
import com.mycompany.payroll.model.Leave;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isuru Sankajith
 */
public class LeaveListForm extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeListForm
     */
    public LeaveListForm() {
        initComponents();
        findAllLeaves();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLeave = new javax.swing.JTable();
        AddEmployeetxt = new javax.swing.JButton();
        UpdateEmployeeForm = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee From");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Leave List");

        tblLeave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leave ID", "Employee ID", "Leave Date", "Leave Type", "Reason"
            }
        ));
        tblLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeaveMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLeave);

        AddEmployeetxt.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt.setText("Add new");
        AddEmployeetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxtActionPerformed(evt);
            }
        });

        UpdateEmployeeForm.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm.setText("Update");
        UpdateEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateEmployeeForm)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateEmployeeForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddEmployeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeFormActionPerformed
        try {
            int row = tblLeave.getSelectedRow();
            int leaveID = 0;
            if (row >= 0) {
                leaveID = Integer.parseInt(tblLeave.getModel().getValueAt(row, 0).toString());
            }
            Leave leave = new Leave();
            leave.setEmployeeId(leaveID);
            LeaveController leaveController = new LeaveController();
            List<Leave> lstLeave = leaveController.findLeavedetailsForID(leave);
            Leave e = new Leave();
            for (int i = 0; i < lstLeave.size(); i++) {
                e = lstLeave.get(i);
            }
            UpdateLeaveForm updateLeaveForm = new UpdateLeaveForm(e);
            updateLeaveForm.setVisible(true);
            updateLeaveForm.setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateEmployeeFormActionPerformed

    private void AddEmployeetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxtActionPerformed
        LeaveForm addEmployeeFrom= new LeaveForm();
        addEmployeeFrom.setVisible(true);
        addEmployeeFrom.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxtActionPerformed

    private void tblLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeaveMouseClicked
        try {
            int row = tblLeave.getSelectedRow();
            int leaveID = 0;
            if (row >= 0) {
                leaveID = Integer.parseInt(tblLeave.getModel().getValueAt(row, 0).toString());
            }
            Leave leave = new Leave();
            leave.setEmployeeId(leaveID);
            LeaveController leaveController = new LeaveController();
            List<Leave> lstLeave = leaveController.findLeavedetailsForID(leave);
            Leave e = new Leave();
            for (int i = 0; i < lstLeave.size(); i++) {
                e = lstLeave.get(i);
            }
            UpdateLeaveForm updateLeaveForm = new UpdateLeaveForm(e);
            updateLeaveForm.setVisible(true);
            updateLeaveForm.setLocationRelativeTo(null);

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblLeaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeetxt;
    private javax.swing.JButton UpdateEmployeeForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLeave;
    // End of variables declaration//GEN-END:variables

    private void findAllLeaves() {
        DefaultTableModel dtm = (DefaultTableModel) tblLeave.getModel();
        dtm.setRowCount(0);
        try {
            LeaveController leaveController = new LeaveController();
            List<Leave> lstLeaves = leaveController.findAllLeaveDetails();

            for (int i = 0; i < lstLeaves.size(); i++) {
                Leave e = lstLeaves.get(i);
                Object[] data = {e.getLeaveId(), e.getEmployeeId(), e.getLeaveDate(), e.getType_name(), e.getReason()};
                dtm.addRow(data);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
