/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.payroll.view;

import com.mycompany.payroll.controller.EmployeeCategoryController;
import com.mycompany.payroll.controller.EmployeeTypeController;
import com.mycompany.payroll.controller.HolidayController;
import com.mycompany.payroll.controller.LeaveTypeController;
import com.mycompany.payroll.controller.ShiftController;
import com.mycompany.payroll.model.EmployeeCategory;
import com.mycompany.payroll.model.EmployeeType;
import com.mycompany.payroll.model.Holiday;
import com.mycompany.payroll.model.LeaveType;
import com.mycompany.payroll.model.Shift;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isuru Sankajith
 */
public class SettingsForm extends javax.swing.JPanel {

    /**
     * Creates new form SettingsForm
     */
    public SettingsForm() {
        initComponents();
        findAllEmployeeTypes();
        findAllLeaveTypes();
        findALLEmployeeCategory();
        findAllShift();
        findAllHolidays();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tblLeaveType1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEmployeeType = new javax.swing.JTable();
        AddEmployeetxt2 = new javax.swing.JButton();
        UpdateEmployeeForm2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmblLeaveType = new javax.swing.JTable();
        AddEmployeetxt1 = new javax.swing.JButton();
        UpdateEmployeeForm1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cmbEmployeeCategory = new javax.swing.JTable();
        AddEmployeetxt = new javax.swing.JButton();
        UpdateEmployeeForm = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        UpdateEmployeeForm3 = new javax.swing.JButton();
        AddEmployeetxt3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblShift = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblHoliday = new javax.swing.JTable();
        AddEmployeetxt4 = new javax.swing.JButton();
        UpdateEmployeeForm4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ID");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cancel_1.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblLeaveType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tblEmployeeType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type ID", "Type Name", "Leave Count"
            }
        ));
        jScrollPane4.setViewportView(tblEmployeeType);
        if (tblEmployeeType.getColumnModel().getColumnCount() > 0) {
            tblEmployeeType.getColumnModel().getColumn(1).setResizable(false);
        }

        AddEmployeetxt2.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt2.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt2.setText("Add new");
        AddEmployeetxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxt2ActionPerformed(evt);
            }
        });

        UpdateEmployeeForm2.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm2.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm2.setText("Update");
        UpdateEmployeeForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeForm2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateEmployeeForm2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployeetxt2)
                    .addComponent(UpdateEmployeeForm2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblLeaveType1.addTab("Employee Type", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cmblLeaveType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leave ID", "Type Name", "Leave Count"
            }
        ));
        jScrollPane3.setViewportView(cmblLeaveType);
        if (cmblLeaveType.getColumnModel().getColumnCount() > 0) {
            cmblLeaveType.getColumnModel().getColumn(1).setResizable(false);
        }

        AddEmployeetxt1.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt1.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt1.setText("Add new");
        AddEmployeetxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxt1ActionPerformed(evt);
            }
        });

        UpdateEmployeeForm1.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm1.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm1.setText("Update");
        UpdateEmployeeForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeForm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateEmployeeForm1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployeetxt1)
                    .addComponent(UpdateEmployeeForm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblLeaveType1.addTab("Leave Type", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cmbEmployeeCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name", "Is Ot Allowed"
            }
        ));
        jScrollPane2.setViewportView(cmbEmployeeCategory);
        if (cmbEmployeeCategory.getColumnModel().getColumnCount() > 0) {
            cmbEmployeeCategory.getColumnModel().getColumn(1).setResizable(false);
        }

        AddEmployeetxt.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt.setText("Add new");
        AddEmployeetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxtActionPerformed(evt);
            }
        });

        UpdateEmployeeForm.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm.setText("Update");
        UpdateEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateEmployeeForm))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployeetxt)
                    .addComponent(UpdateEmployeeForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblLeaveType1.addTab("Employee Category", jPanel2);

        UpdateEmployeeForm3.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm3.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm3.setText("Update");
        UpdateEmployeeForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeForm3ActionPerformed(evt);
            }
        });

        AddEmployeetxt3.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt3.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt3.setText("Add new");
        AddEmployeetxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxt3ActionPerformed(evt);
            }
        });

        tblShift.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shift Id", "Shift Name", " StarTime", "End Time"
            }
        ));
        jScrollPane5.setViewportView(tblShift);
        if (tblShift.getColumnModel().getColumnCount() > 0) {
            tblShift.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateEmployeeForm3))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployeetxt3)
                    .addComponent(UpdateEmployeeForm3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblLeaveType1.addTab("Shift", jPanel7);

        tblHoliday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Holiday Id", "Hours", "Date", "Reson"
            }
        ));
        jScrollPane6.setViewportView(tblHoliday);
        if (tblHoliday.getColumnModel().getColumnCount() > 0) {
            tblHoliday.getColumnModel().getColumn(1).setResizable(false);
        }

        AddEmployeetxt4.setBackground(new java.awt.Color(0, 102, 102));
        AddEmployeetxt4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddEmployeetxt4.setForeground(new java.awt.Color(204, 204, 204));
        AddEmployeetxt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddEmployeetxt4.setText("Add new");
        AddEmployeetxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeetxt4ActionPerformed(evt);
            }
        });

        UpdateEmployeeForm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm4.setText("Update");
        UpdateEmployeeForm4.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm4.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeForm4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddEmployeetxt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateEmployeeForm4))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployeetxt4)
                    .addComponent(UpdateEmployeeForm4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblLeaveType1.addTab("Holidays", jPanel8);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Master Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblLeaveType1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblLeaveType1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeFormActionPerformed
        UpdateEmployeeCategory updateEmployeeCategory = new UpdateEmployeeCategory();
        updateEmployeeCategory.setVisible(true);
        updateEmployeeCategory.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeFormActionPerformed

    private void AddEmployeetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxtActionPerformed
        AddEmployeeCategory addEmployeeCategory = new AddEmployeeCategory();
        addEmployeeCategory.setVisible(true);
        addEmployeeCategory.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxtActionPerformed

    private void AddEmployeetxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxt1ActionPerformed
      AddLeaveType addLeaveType = new AddLeaveType();
      addLeaveType.setVisible(true);
      addLeaveType.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxt1ActionPerformed

    private void UpdateEmployeeForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeForm1ActionPerformed
      UpdateLeaveType updateLeaveType = new UpdateLeaveType();
      updateLeaveType.setVisible(true);
      updateLeaveType.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeForm1ActionPerformed

    private void AddEmployeetxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxt2ActionPerformed
       AddEmployeeType addEmployeeType = new AddEmployeeType();
       addEmployeeType.setVisible(true);
       addEmployeeType.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxt2ActionPerformed

    private void UpdateEmployeeForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeForm2ActionPerformed
        UpdateEmployeeType updateEmployeeType = new UpdateEmployeeType();
        updateEmployeeType.setVisible(true);
        updateEmployeeType.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeForm2ActionPerformed

    private void UpdateEmployeeForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeForm3ActionPerformed
        UpdateShiftType updateShiftType = new UpdateShiftType();
        updateShiftType.setVisible(true);
        updateShiftType.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeForm3ActionPerformed

    private void AddEmployeetxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxt3ActionPerformed
        AddShiftType addShiftType = new AddShiftType();
        addShiftType.setVisible(true);
        addShiftType.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxt3ActionPerformed

    private void AddEmployeetxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeetxt4ActionPerformed
       AddHolidayType addHolidayType = new AddHolidayType();
       addHolidayType.setVisible(true);
       addHolidayType.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddEmployeetxt4ActionPerformed

    private void UpdateEmployeeForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeForm4ActionPerformed
      UpdateHolidayType updateHolidayType = new UpdateHolidayType();
      updateHolidayType.setVisible(true);
      updateHolidayType.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeForm4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeetxt;
    private javax.swing.JButton AddEmployeetxt1;
    private javax.swing.JButton AddEmployeetxt2;
    private javax.swing.JButton AddEmployeetxt3;
    private javax.swing.JButton AddEmployeetxt4;
    private javax.swing.JButton UpdateEmployeeForm;
    private javax.swing.JButton UpdateEmployeeForm1;
    private javax.swing.JButton UpdateEmployeeForm2;
    private javax.swing.JButton UpdateEmployeeForm3;
    private javax.swing.JButton UpdateEmployeeForm4;
    private javax.swing.JTable cmbEmployeeCategory;
    private javax.swing.JTable cmblLeaveType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblEmployeeType;
    private javax.swing.JTable tblHoliday;
    private javax.swing.JTabbedPane tblLeaveType1;
    private javax.swing.JTable tblShift;
    // End of variables declaration//GEN-END:variables

    private void findAllEmployeeTypes() {
        DefaultTableModel dtm = (DefaultTableModel)tblEmployeeType.getModel();
        dtm.setRowCount(0);
        try{
            EmployeeTypeController objEmployeeTypeController = new EmployeeTypeController();
            List<EmployeeType>employeeTypes = objEmployeeTypeController.findAllEmployeeType();
            
            for(int i=0; i<employeeTypes.size(); i++){
                EmployeeType e = employeeTypes.get(i);
                Object[]data = {e.getEmployeetypeid(),e.getTypename(),e.getLeavecount()};
                dtm.addRow(data);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    private void findAllLeaveTypes() {
       DefaultTableModel dtm = (DefaultTableModel) cmblLeaveType.getModel();
       dtm.setRowCount(0);
       try{
           LeaveTypeController objLeaveTypeController = new LeaveTypeController();
                List<LeaveType> leaveTypes = objLeaveTypeController.findAllLeaveType();
                
                for(int i=0;i<leaveTypes.size();i++){
                   LeaveType l = leaveTypes.get(i);
                   Object[]data = {l.getLeave_type_id(),l.getType_name(),l.getNo_of_hour()};
                   dtm.addRow(data);
                }
                
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }

    private void findALLEmployeeCategory() {
        DefaultTableModel dtm = (DefaultTableModel)cmbEmployeeCategory.getModel();
        dtm.setRowCount(0);
        try{
            EmployeeCategoryController objEmployeeCategoryController= new EmployeeCategoryController();
            List<EmployeeCategory>employeeCategory=objEmployeeCategoryController.findAllEmployeeCategory();
            
            for(int i=0;i<employeeCategory.size();i++){
                EmployeeCategory e = employeeCategory.get(i);
                Object[] data ={e.getEmployee_category_id(),e.getCategory_name(),e.getIs_ot_allowed()};
                dtm.addRow(data);
            }
        
        }catch(Exception ex){
            ex.printStackTrace();
    }
    }

    private void findAllShift() {
     DefaultTableModel dtm = (DefaultTableModel)tblShift.getModel();
     dtm.setRowCount(0);
        try {
            ShiftController objShiftController = new  ShiftController();
            List<Shift> shifts = objShiftController.findAllShift();
            for (int i = 0; i < shifts.size(); i++) {
                Shift e = shifts.get(i);
                Object[] data = {e.getShift_id(), e.getShift_name(), e.getStart_time(), e.getEnd_time()};
                dtm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void findAllHolidays() {
     DefaultTableModel dtm= (DefaultTableModel)tblHoliday.getModel();
     dtm.setRowCount(0);
        try {
            HolidayController objHolidayController = new HolidayController();
            List<Holiday> holidays = objHolidayController.findAllHoliday();
            
            for (int i = 0; i <holidays.size(); i++) {
                Holiday e = holidays.get(i);
                Object[]data = {e.getHoliday_id(),e.getHours(),e.getDate(),e.getReason()};
                dtm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
