/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.payroll.view;

import com.mycompany.payroll.controller.EmployeeController;
import com.mycompany.payroll.controller.TransactionController;
import com.mycompany.payroll.controller.TransactionDetailController;
import com.mycompany.payroll.model.Employee;
import com.mycompany.payroll.model.Transaction;
import com.mycompany.payroll.model.TransactionDetail;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isuru Sankajith
 */
public class TransactionListForm extends javax.swing.JPanel {

    /**
     * Creates new form TransactionListForm
     */
    public TransactionListForm() {
        initComponents();
        findAllTransaction();
        AddAttendance.setVisible(false);
        UpdateEmployeeForm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransactionDetail = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransactionHeader = new javax.swing.JTable();
        AddAttendance = new javax.swing.JButton();
        UpdateEmployeeForm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        tblTransactionDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Detail Id", "Transaction ID", "Description", "Amount"
            }
        ));
        jScrollPane3.setViewportView(tblTransactionDetail);

        tblTransactionHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Id", "Employee Id", "Gross Salary", "Net Salary", "Salary Forl", "Transaction Time"
            }
        ));
        tblTransactionHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransactionHeaderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTransactionHeader);

        AddAttendance.setBackground(new java.awt.Color(0, 102, 102));
        AddAttendance.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddAttendance.setForeground(new java.awt.Color(204, 204, 204));
        AddAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/addnew_2.png"))); // NOI18N
        AddAttendance.setText("Add new");
        AddAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAttendanceActionPerformed(evt);
            }
        });

        UpdateEmployeeForm.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEmployeeForm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateEmployeeForm.setForeground(new java.awt.Color(204, 204, 204));
        UpdateEmployeeForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/update_1.png"))); // NOI18N
        UpdateEmployeeForm.setText("Update");
        UpdateEmployeeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeFormActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Transaction List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddAttendance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateEmployeeForm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddAttendance)
                    .addComponent(UpdateEmployeeForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAttendanceActionPerformed
      AddTransactionForm addTransactionForm = new AddTransactionForm();
      addTransactionForm.setVisible(true);
      addTransactionForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddAttendanceActionPerformed

    private void UpdateEmployeeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeFormActionPerformed
       UpdateTransactionForm updateTransactionForm = new UpdateTransactionForm();
       updateTransactionForm.setVisible(true);
       updateTransactionForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_UpdateEmployeeFormActionPerformed

    private void tblTransactionHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransactionHeaderMouseClicked
        try {
            int row = tblTransactionHeader.getSelectedRow();
            int transactionId = 0;
            if (row >= 0) {
                transactionId = Integer.parseInt(tblTransactionHeader.getModel().getValueAt(row, 0).toString());
            }
            TransactionDetail transactionDetail = new TransactionDetail();
            transactionDetail.setTransaction_id(transactionId);
            TransactionDetailController transactionDetailController = new TransactionDetailController();
            List<TransactionDetail> lsttTransactionDetails = transactionDetailController.findTransactionDetailsForId(transactionDetail);
             
            DefaultTableModel dtmDetail = (DefaultTableModel) tblTransactionDetail.getModel();
            dtmDetail.setRowCount(0);
            
            TransactionDetail e = new TransactionDetail();
            for (int i = 0; i < lsttTransactionDetails.size(); i++) {
                e = lsttTransactionDetails.get(i);
                Object[] data = {e.getTransaction_detail_id(), e.getTransaction_id(), e.getDescription(), e.getAmount()};
                dtmDetail.addRow(data);
            }

        } catch (Exception ex) {
            Logger.getLogger(EmployeeListForm.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblTransactionHeaderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAttendance;
    private javax.swing.JButton UpdateEmployeeForm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTransactionDetail;
    private javax.swing.JTable tblTransactionHeader;
    // End of variables declaration//GEN-END:variables

    private void findAllTransaction() {
        DefaultTableModel dtm = (DefaultTableModel) tblTransactionHeader.getModel();
        dtm.setRowCount(0);
        try {
            TransactionController transactionController = new TransactionController();
            List<Transaction> lstTransactions = transactionController.findAllTransaction();

            for (int i = 0; i < lstTransactions.size(); i++) {
                Transaction transaction = lstTransactions.get(i);
                Object[] data = {transaction.getTransaction_id(), transaction.getEmployee_id(), transaction.getGross_salary(), transaction.getNet_salary(), transaction.getSalary_for(), transaction.getTransaction_time()};
                dtm.addRow(data);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
